numero = int(input('digite um numero:'))
numx1 = numero * 1
numx2 = numero * 2
numx3 = numero * 3
numx4 = numero * 4
numx5 = numero * 5
numx6 = numero * 6
numx7 = numero * 7
numx8 = numero * 8
numx9 = numero * 9
numx10 = numero * 10
print('1 x {} = {}'.format(numero, numx1))
print('2 x {} = {}'.format(numero, numx2))
print('3 x {} = {}'.format(numero, numx3))
print('4 x {} = {}'.format(numero, numx4))
print('5 x {} = {}'.format(numero, numx5))
print('6 x {} = {}'.format(numero, numx6))
print('7 x {} = {}'.format(numero, numx7))
print('8 x {} = {}'.format(numero, numx8))
print('9 x {} = {}'.format(numero, numx9))
print('10 x {} = {}'.format(numero, numx10))
